rancher/hyperkube

.drone.yml
Dockerfile.arm64

This PR includes the following changes.
- Added the arm64 dockerfile for build arm64 docker image.
- Added the drone1.0 config file for multiarch CICD.
The config file `.drone-multiarch.yml` and the rancher `dockerhub_username` and `dockerhub_password` need to be set to this repo in drone-1.0 server.
Issue
https://github.com/rancher/rancher/issues/16461
https://github.com/rancher/rancher/issues/16518

Add arm64 docker file and drone multiarch CICD support for v1.13 k8s 

---

.drone.yml
Dockerfile.arm64

This PR includes the following changes.
- Added the arm64 dockerfile for build arm64 docker image.
- Added the drone1.0 config file for multiarch CICD.
The config file `.drone-multiarch.yml` and the rancher `dockerhub_username` and `dockerhub_password` need to be set to this repo in drone-1.0 server.
Issue
https://github.com/rancher/rancher/issues/16461
https://github.com/rancher/rancher/issues/16518

Add arm64 docker file and drone multiarch CICD support for v1.12 k8s

---

.drone.yml
Dockerfile.arm64

This PR includes the following changes.
- Added the arm64 dockerfile for build arm64 docker image.
- Added the drone1.0 config file for multiarch CICD.
The config file `.drone-multiarch.yml` and the rancher `dockerhub_username` and `dockerhub_password` need to be set to this repo in drone-1.0 server.
Issue
https://github.com/rancher/rancher/issues/16461
https://github.com/rancher/rancher/issues/16518

Add arm64 docker file and drone multiarch CICD support for v1.11 k8s

---

Dockerfile
Dockerfile.arm64
Dockerfile.windows

Need a `rancher/hyperkube:v1.15.12` image for [this issue](https://github.com/rancher/rancher/issues/26958)

update k8s version for new hyperkube image (v1.15.11 -> v1.15.12)

---

Dockerfile
Dockerfile.arm64
Dockerfile.windows

- Update k8s version to v1.16.12
- Remove `update-alternatives` since new base image includes [iptables-wrapper](https://github.com/kubernetes/kubernetes/blob/release-1.17/build/debian-iptables/Dockerfile)

Update k8s version to v1.16.12

---

Dockerfile
Dockerfile.arm64
Dockerfile.windows

- Update k8s version to v1.17.8
- Remove `update-alternatives` since new base image includes [iptables-wrapper](https://github.com/kubernetes/kubernetes/blob/release-1.17/build/debian-iptables/Dockerfile)

Update k8s version to v1.17.8

---

Dockerfile
Dockerfile.arm64
Dockerfile.windows

- Update k8s version to v1.18.5
- Remove `update-alternatives` since new base image includes [iptables-wrapper](https://github.com/kubernetes/kubernetes/blob/release-1.17/build/debian-iptables/Dockerfile)

Update k8s version to v1.18.5

---

Makefile

Signed-off-by: Chris Kim <oats87g@gmail.com>

Update Makefile to support k8s-binaries format

---

Dockerfile
Dockerfile.windows
Makefile

Bump hyperkube to v1.19.0
https://github.com/rancher/rancher/issues/26717
Signed-off-by: Chris Kim <oats87g@gmail.com>

Bump to v1.19.0 and use v0.0.1 of rancher/hyperkube-base

---

Dockerfile
Dockerfile.arm64
Dockerfile.windows

Repository has changed to be community owned under the domain `{asia,eu,us}.gcr.io/k8s-artifacts-prod`.
`gcr.io/google-containers`has also changed to `k8s.gcr.io`, but solely for backwards compatibility reasons and not for future use.

Update hyperkube to v1.18.8

---

Dockerfile
Dockerfile.arm64
Dockerfile.windows

Repository has changed to be community owned under the domain `{asia,eu,us}.gcr.io/k8s-artifacts-prod`.
`gcr.io/google-containers`has also changed to `k8s.gcr.io`, but solely for backwards compatibility reasons and not for future use.

Update hyperkube to v1.16.14

---

Dockerfile
Dockerfile.arm64
Dockerfile.windows

Repository has changed to be community owned under the domain `{asia,eu,us}.gcr.io/k8s-artifacts-prod`.
`gcr.io/google-containers`has also changed to `k8s.gcr.io`, but solely for backwards compatibility reasons and not for future use.

Update hyperkube to v1.17.11

---

.drone.yml
manifest.tmpl

Adds support for windows 2004
https://github.com/rancher/rancher/issues/27451

[v1.19] Adding Windows 2004

---

.drone.yml
Dockerfile.windows.20H2
manifest.tmpl

https://github.com/rancher/rancher/issues/30701

Adding Windows 20H2 Builds

---

.drone.yml

* This builds all image on PR, it was just cloning the repository before which gave the impression something was being done while nothing was done and it was always green
* Moved to images located in `rancher/` vs `luthermonson/`, similar to https://github.com/rancher/rancher/pull/32434

Build on pull request

---

.drone.yml
manifest.tmpl

- Remove Windows Server 2004 SAC from drone and manifest template
- bump to dapper 0.5.7

[v1.21] remove windows server 2004 SAC build step

---

.drone.yml
manifest.tmpl

- Remove Windows Server 2004 SAC from drone and manifest template
- bump to dapper 0.5.7

[v1.20] remove windows server 2004 SAC build step

---

.drone.yml
manifest.tmpl

- Remove Windows Server 2004 SAC from drone and manifest template
- bump to dapper 0.5.7

[v1.19] remove windows server 2004 SAC build step

---

Dockerfile

Do not merge before rancher/hyperkube-base#7
Related: rancher/rancher#35709
Tag should be: `v1.22.5-rancher2`

[v1.22] Update hyperkube-base

---

Dockerfile

Do not merge before rancher/hyperkube-base#7
Related: rancher/rancher#35709
Tag should be: `v1.21.8-rancher2`

[v1.21] Update hyperkube-base

---

Dockerfile

Do not merge before https://github.com/rancher/hyperkube-base/pull/7
Related: https://github.com/rancher/rancher/issues/35709
Tag should be: `v1.20.14-rancher2`

[v1.20] Update hyperkube-base

---

Dockerfile
Makefile

Downloading from https://github.com/rancher/kubernetes/releases/tag/v1.24.10-rc.1-rancher1, final release tag `v1.24.10` will be updated later once drone logic for rancher/kubernetes is added. 
The rc tag has this fix https://github.com/rancher/kubernetes/pull/74

[v1.24] use custom kubelet from rancher/kubernetes

---

Makefile

Forward port change from https://github.com/rancher/hyperkube/pull/305 for v1.25.

[v1.25] use custom kubelet from rancher/kubernetes

---

CODEOWNERS
README.md

- Adds `README` to explain what this is, does, and especially the kubelet binary source change and since when.
- Adds `CODEOWNERS`, although this won't work as it needs to be in each branch (I will do that later), it will still make clear who is responsible for this repository

Add README and CODEOWNERS

---

.github/workflows/fossa.yaml

[1.29] update the workflow for FOSSA

[1.29] update the workflow for FOSSA

---

.github/workflows/fossa.yaml

[1.28] update the workflow for FOSSA

[1.28] update the workflow for FOSSA

---

.github/workflows/release.yaml

Access to original path has been fixed, reverting prime changes to use scoped credentials again. 
This reverts commit bfffcd546d59c8e7932b483cb162d97fc9dbac93.

[v1.32] Revert prime registry path
