rancher/hyperkube

- Dockerfile.windows
> Download Azure client on Windows for 1.16

- Dockerfile.windows
> Download Azure client on Windows for 1.14

- Dockerfile.windows
> Download Azure client on Windows for 1.15

- Dockerfile
- Dockerfile.arm64
https://github.com/rancher/rancher/issues/22802
> Install glusterfs client from stretch-backports

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> K8s v1.17.2

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> K8s v1.16.6

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> K8s v1.15.9

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> K8s v1.14.10

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> K8s v1.17.3

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> K8s v1.16.7

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> K8s v1.15.10

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> k8s v1.17.6

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> k8s v1.16.10

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
Version bump for new k8s v1.17.7
> [1.17] Update to k8s v1.17.7

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
Version bump for new k8s v1.16.11
> [1.16] Update to k8s v1.16.11

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
Version bump for new k8s v1.18.4
> [1.18] Update to k8s v1.18.4

- Dockerfile
- Dockerfile.arm64
https://github.com/rancher/rancher/issues/27639
> [v1.16] Update Dockerfiles for stretch -> buster change

- Dockerfile
- Dockerfile.arm64
https://github.com/rancher/rancher/issues/27639
> [v1.17] Update Dockerfiles for stretch -> buster change

- Dockerfile
- Dockerfile.arm64
https://github.com/rancher/rancher/issues/27639
> [v1.18] Update Dockerfiles for stretch -> buster change

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
> Update hyperkube to v1.16.15

- .drone.yml
- manifest.tmpl
Adds support for windows 2004
https://github.com/rancher/rancher/issues/27451
> [v1.16] Adding Windows 2004

- .drone.yml
- manifest.tmpl
Adds support for windows 2004
https://github.com/rancher/rancher/issues/27451
> [v1.17] Adding Windows 2004

- .drone.yml
- manifest.tmpl
Adds support for windows 2004
https://github.com/rancher/rancher/issues/27451
> [v1.18] Adding Windows 2004

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
Make changes to support build for `v1.17.13`
> Add k8s v1.17.13

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
Make changes to support build for `v1.18.10`
> Add k8s v1.18.10

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
https://github.com/rancher/rancher/issues/29981
> Add k8s v1.17.14

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
https://github.com/rancher/rancher/issues/29981
> Add k8s v1.18.12

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
https://github.com/rancher/rancher/issues/30221
https://github.com/rancher/rancher/issues/30222
> Add k8s v1.18.13

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
https://github.com/rancher/rancher/issues/30221
https://github.com/rancher/rancher/issues/30222
> Add k8s v1.17.5

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
https://github.com/rancher/rancher/issues/30222
https://github.com/rancher/rancher/issues/30223
> Add k8s v1.17.16

- Dockerfile
- Dockerfile.arm64
- Dockerfile.windows
https://github.com/rancher/rancher/issues/30221
> Add k8s v1.18.14

- .drone.yml
- Dockerfile.windows.20H2
- manifest.tmpl
https://github.com/rancher/rancher/issues/30701
> [v1.18] Adding Windows 20H2 Builds

- .drone.yml
- Dockerfile.windows.20H2
- manifest.tmpl
https://github.com/rancher/rancher/issues/30701
> [v1.17] Adding Windows 20H2 Builds

- .drone.yml
- Dockerfile.windows.20H2
- manifest.tmpl
https://github.com/rancher/rancher/issues/30701
> [v1.16] Adding Windows 20H2 Builds

- Dockerfile
- Dockerfile.windows
- Dockerfile.windows.20H2
https://github.com/rancher/rancher/issues/31782
https://github.com/rancher/rancher/issues/31781
> Add k8s 1.18.17

- Dockerfile
- Dockerfile.windows
- Dockerfile.windows.20H2
https://github.com/rancher/rancher/issues/32173
https://github.com/rancher/rancher/issues/32178
> Add k8s v1.18.18

- .drone.yml
Backport of https://github.com/rancher/hyperkube/pull/193
> [v1.21] Build on pull request

- .drone.yml
Backport of https://github.com/rancher/hyperkube/pull/193
> [v1.20] Build on pull request

- .drone.yml
Backport of https://github.com/rancher/hyperkube/pull/193
> [v1.19] Build on pull request

- Dockerfile.windows
- Dockerfile.windows.20H2
- Makefile
https://github.com/rancher/rancher/issues/33114
> [v1.22] Add v1.22.0-beta.1

- Dockerfile.windows
- Dockerfile.windows.20H2
- Makefile
https://github.com/rancher/rancher/issues/33114
> Add v1.22.0-rc.0

- .drone.yml
- manifest.tmpl
- Remove Windows Server 2004 SAC from drone and manifest template
- bump to dapper 0.5.7
> [v1.22] remove windows server 2004 SAC build step

- Dockerfile
Related to https://github.com/rancher/rancher/issues/36021
> update base image to 0.0.14

- Dockerfile
Related: https://github.com/rancher/rancher/issues/40508
Depends on hyperkube-base tag: https://github.com/rancher/hyperkube-base/pull/11
> [v1.25] Bump hyperkube-base

- Dockerfile
Related: https://github.com/rancher/rancher/issues/40508
Depends on hyperkube-base tag: https://github.com/rancher/hyperkube-base/pull/11
> [v1.24] Bump hyperkube-base

- Dockerfile
Related: https://github.com/rancher/rancher/issues/40508
Depends on hyperkube-base tag: https://github.com/rancher/hyperkube-base/pull/11
> [v1.23] Bump hyperkube-base

- Makefile
Issues: 
2.7 - https://github.com/rancher/rancher/issues/38816
2.6 - https://github.com/rancher/rancher/issues/40596
> [v1.24] download kubelet from release tag

- Makefile
Issues:
2.7 - https://github.com/rancher/rancher/issues/38816
2.6 - https://github.com/rancher/rancher/issues/40596
> [v1.25] download kubelet from release tag

- Makefile
Related: https://github.com/rancher/hyperkube/pull/309#pullrequestreview-1382593696
> [v1.25] Forward-port `v1.25-custom` branch changes into `v1.25`

- Dockerfile
issue: https://github.com/rancher/rancher/issues/43074
> bumped hyperkube-base to v0.0.19

- .github/workflows/release.yaml
> [1.27] fix indentation

- .github/workflows/release.yaml
> [1.29] fix indentation

- .github/workflows/release.yaml
> [1.28] fix indentation

- .github/workflows/fossa.yaml
[1.27] update the workflow for FOSSA
> [1.27] update the workflow for FOSSA
